secret: secret000
privateKeyLocation: private.pem
publicKeyLocation: public.pem
redisAddr: realworld-docker-compose-redis:6379
mysqlDSN: root:12345678@(realworld-docker-compose-mysql:3306)/realworld?parseTime=true